export const PUBLIC_USER_API = "PUBLIC_USER_API";
export const PUBLIC_USER_API_SUCCESS = "PUBLIC_USER_API_SUCCESS";

export const PUBLIC_USER_STORES = "PUBLIC_USER_STORES"
export const PUBLIC_USER_STORES_SUCCESS = "PUBLIC_USER_STORES_SUCCESS"

export const PUBLIC_USER_OFFERS = "PUBLIC_USER_OFFERS"
export const PUBLIC_USER_OFFERS_SUCCESS = "PUBLIC_USER_OFFERS_SUCCESS"

export const PUBLIC_USER_DEALS = "PUBLIC_USER_DEALS"
export const PUBLIC_USER_DEALS_SUCCESS = "PUBLIC_USER_DEALS_SUCCESS"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"

export const ALL_CATEGORY_REQUEST = "ALL_CATEGORY_REQUEST"
export const PARENT_CATEGORY_SUCCESS = "PARENT_CATEGORY_SUCCESS"
export const ALL_CATEGORY_SUCCESS = "ALL_CATEGORY_SUCCESS"

export const STORE_DETAIL_REQUEST = "STORE_DETAIL_REQUEST"
export const STORE_DETAIL_SUCCESS = "STORE_DETAIL_SUCCESS"

